name: Build Windows Desktop

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.8'
          channel: stable
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Get Dependencies
        working-directory: simple_live_app
        run: flutter pub get

      # 修复 MSVC coroutine 兼容问题
      - name: Setup MSVC flags
        shell: powershell
        run: |
          echo "CMAKE_CXX_FLAGS=/D_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNING" >> $env:GITHUB_ENV

      - name: Build Windows
        working-directory: simple_live_app
        run: |
          flutter build windows --release

      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: simple-live-windows-release
          path: simple_live_app/build/windows/x64/runner/Release
